name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          cat << EOF > /etc/apt/sources.list
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ bionic main universe
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main universe
          deb [arch=amd64] http://security.ubuntu.com/ubuntu/ bionic-security main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ bionic-security main universe
          EOF
          dpkg --add-architecture arm64
          apt update
          apt install --no-install-recommends -y ca-certificates zip build-essential gcc-aarch64-linux-gnu
      - name: Create dist dir
        run: mkdir dist
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Build x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          apt install --no-install-recommends -y libgtk-3-dev libappindicator3-dev
          go build -o ./dist/tray-linux-amd64 -ldflags "-s -w" tray.go
          apt remove -y libgtk-3-dev libappindicator3-dev
      - name: Build arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          GOHOSTARCH: amd64
          CC: aarch64-linux-gnu-gcc
          CC_FOR_TARGET: gcc-aarch64-linux-gnu
        run: |
          apt install --no-install-recommends -y libgtk-3-dev:arm64 libappindicator3-dev:arm64
          go build -o ./dist/tray-linux-arm64 -ldflags "-s -w" tray.go
          apt remove -y libgtk-3-dev:arm64 libappindicator3-dev:arm64
      - name: Upload linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: tray_linux
          path: ./dist