name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Build Linux Binaries
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install gtk3
        run: |
          sudo apt-get install libgtk-3-dev libappindicator3-dev gcc-aarch64-linux-gnu
          mkdir dist
      - name: Setup Go environment
        uses: actions/setup-go@v3
      - name: Build x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o ./dist/tray-linux-amd64 -ldflags "-s -w" tray.go
      - name: Build arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          GOHOSTARCH: amd64
          CC: aarch64-linux-gnu-gcc
          CC_FOR_TARGET: gcc-aarch64-linux-gnu
        run: go build -o ./dist/tray-linux-arm64 -ldflags "-s -w" tray.go
      - name: Upload linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: tray_linux
          path: ./dist