name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target-os: linux
            binary: ./tray_linux_release
            rawName: tray_linux_release
          - os: windows-latest
            target-os: windows
            binary: .\tray_windows_release.exe
            ext: .exe
            rawName: tray_windows_release.exe
          - os: macos-latest
            target-os: darwin
            binary: ./tray_darwin_release
            rawName: tray_darwin_release
    steps:
    - uses: actions/checkout@master

    - name: Install gtk3
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: sudo apt-get install libgtk-3-dev libappindicator3-dev

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    - name: Build x64
      run: env GOOS=${{ matrix.target-os }} GOARCH=amd64 go build -o ./tray-${{ matrix.target-os }}-adm64${{ matrix.ext }} -ldflags "-s -w" tray.go
    - name: Build arm64
      if: ${{ matrix.os != 'windows-latest' }}
      run: env GOOS=${{ matrix.target-os }} GOARCH=arm64 go build -o ./tray-${{ matrix.target-os }}-arm64${{ matrix.ext }} -ldflags "-s -w" tray.go

    # - name: Upload a Release Asset
    #   uses: actions/upload-release-asset@v1.0.2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: https://uploads.github.com/repos/felixhao28/systray-portable/releases/33386051/assets{?name,label}
    #     asset_path: ${{ matrix.binary }}
    #     asset_name: ${{ matrix.rawName }}
    #     asset_content_type: application/octet-stream
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tray-${{ matrix.target-os }}-adm64${{ matrix.ext }}
        path: ./tray-${{ matrix.target-os }}-adm64${{ matrix.ext }}
    - name: Upload artifact
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: tray-${{ matrix.target-os }}-arm64${{ matrix.ext }}
        path: ./tray-${{ matrix.target-os }}-arm64${{ matrix.ext }}
