name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Build Linux Binaries
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo cat << EOF > /etc/apt/sources.list
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal main universe
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal-updates main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main universe
          deb [arch=amd64] http://security.ubuntu.com/ubuntu/ focal-security main universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-security main universe
          EOF
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install --no-install-recommends -y gcc-aarch64-linux-gnu
      - name: Create dist dir
        run: mkdir dist
      - name: Setup Go environment
        uses: actions/setup-go@v3
      - name: Build x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          sudo apt install --no-install-recommends -y libgtk-3-dev libappindicator3-dev
          go build -o ./dist/tray-linux-amd64 -ldflags "-s -w" tray.go
          sudo apt remove -y libgtk-3-dev libappindicator3-dev
      - name: Build arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          GOHOSTARCH: amd64
          CC: aarch64-linux-gnu-gcc
          CC_FOR_TARGET: gcc-aarch64-linux-gnu
        run: |
          sudo apt install --no-install-recommends -y libgtk-3-dev:arm64 libappindicator3-dev:arm64
          go build -o ./dist/tray-linux-arm64 -ldflags "-s -w" tray.go
          sudo apt remove -y libgtk-3-dev:arm64 libappindicator3-dev:arm64
      - name: Upload linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: tray_linux
          path: ./dist